apiVersion: v1
kind: Namespace
metadata:
  name: demo-a
  labels:
    env: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-b
  labels:
    env: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-a
  labels:
    app: api
    tier: backend
data:
  LOG_LEVEL: debug
  FEATURE_FLAG_X: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: demo-a
  labels:
    app: api
type: Opaque
stringData:
  token: demo-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: demo-a
  labels:
    app: api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
        - name: api
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: demo-a
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: worker-a
  namespace: demo-a
  labels:
    app: worker
    tier: batch
spec:
  containers:
    - name: worker
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-job
  namespace: demo-b
  labels:
    app: bootstrap
spec:
  template:
    metadata:
      labels:
        app: bootstrap
    spec:
      restartPolicy: Never
      containers:
        - name: bootstrap
          image: busybox:1.36
          command: ["sh", "-c", "echo seeded && sleep 5"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo-b
  labels:
    app: web
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: demo.kql.io/v1alpha1
kind: Widget
metadata:
  name: widget-a
  namespace: demo-a
  labels:
    app: widget
spec:
  owner: team-a
  enabled: true
---
apiVersion: demo.kql.io/v1alpha1
kind: Widget
metadata:
  name: widget-b
  namespace: demo-b
  labels:
    app: widget
spec:
  owner: team-b
  enabled: false
